name: Deploy

on:
  push:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ikeapp"
          heroku_email: "tristan.bourgeois@epitech.eu"
          usedocker: true
          appdir: "web"

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ikeapi"
          heroku_email: "tristan.bourgeois@epitech.eu"
          usedocker: true
          appdir: "back"
